+define+RVFI
+define+FORMAL
+incdir+$rtlRoot
+incdir+$primRoot
$primRoot/prim_ram_1p_pkg.sv
$primRoot/prim_cipher_pkg.sv
$primRoot/prim_lfsr.sv
$primRoot/prim_secded_pkg.sv
$primRoot/prim_secded_inv_39_32_dec.sv
$primRoot/prim_secded_inv_39_32_enc.sv
$rtlRoot/cheri_pkg.sv
$rtlRoot/ibex_pkg.sv
$rtlRoot/cheri_decoder.sv
$rtlRoot/cheri_ex.sv
$rtlRoot/cheri_regfile.sv
$rtlRoot/cheri_trvk_stage.sv
$rtlRoot/cheri_tbre.sv
$rtlRoot/cheri_stkz.sv
$rtlRoot/cheri_tbre_wrapper.sv
$rtlRoot/ibex_fetch_fifo.sv
$rtlRoot/ibex_prefetch_buffer.sv
$rtlRoot/ibex_branch_predict.sv
$rtlRoot/ibex_compressed_decoder.sv
$rtlRoot/ibex_if_stage.sv
$rtlRoot/ibex_controller.sv
$rtlRoot/ibex_decoder.sv
$rtlRoot/ibex_id_stage.sv
$rtlRoot/ibex_load_store_unit.sv
$rtlRoot/ibex_wb_stage.sv
$rtlRoot/ibex_alu.sv
$rtlRoot/ibex_multdiv_fast.sv
$rtlRoot/ibex_multdiv_slow.sv
$rtlRoot/ibex_ex_block.sv
$rtlRoot/ibex_csr.sv
$rtlRoot/ibex_cs_registers.sv
$rtlRoot/ibex_counter.sv
$rtlRoot/ibex_dummy_instr.sv
$rtlRoot/ibex_core.sv
$rtlRoot/ibex_pmp.sv
$rtlRoot/ibexc_top.sv
$verifRoot/tb/cheriot_dv_pkg.sv
$verifRoot/fcov/module_dv_ext.sv
